### ISSUE TITLE
Request to move recurring meeting time

### ISSUE THREAD

**Issue by JssDWt** [BitcoinAndLightningLayerSpecs/meetings#2]
Unfortunately I'm unable to attend the meetings on Wednesdays. If possible, could we move the meeting to Monday, Thursday or Friday between 8UTC and 14UTC? Or any weekday at 19UTC?

**Comment by ZmnSCPxj-jr** [comment]
19UTC is not possible for me.  8UTC to about 12UTC start time is OK for me.

**Comment by SeverinAlexB** [comment]
Group decision: Meetings will be moved to Thursday same time (11UTC).

**Comment by BitcoinErrorLog** [comment]
Calendar invite has been updated

**Comment by JssDWt** [comment]
Thanks
